### ISSUE TITLE
CSV files for labels

### ISSUE THREAD

**Issue by kecol** [lucazanella/AnomalyCLIP#1]
It looks like to be able to run the evaluation it is required any of these files:

- sht_labels.csv
- ucf_labels.csv
- xd_labels.csv

I didn't find them in the data folder. Is there a place to download them?

Thanks!

**Comment by luca-zanella-dvl** [comment]
Hi, thank you for your interest in our work!

You're right, thanks for pointing that out. We mistakenly added the data folder to .gitignore, causing these files to remain untracked by Git. Please pull the repository again, as I have updated other files as well, and try again. Please don't hesitate to reach out if you encounter any further issues.

Thank you once again.

**Comment by kecol** [comment]
Thank you very much @luca-zanella-dvl!
