### ISSUE TITLE
ShanghaiTech anomaly labels

### ISSUE THREAD

**Issue by KyloRen1** [lucazanella/AnomalyCLIP#11]
Hello! Great work.
I am wondering, how did you generate label files for ShanghaiTech dataset, as in original dataset only normal/anomaly labels are available for test split. I saw in [this reply](https://github.com/luca-zanella-dvl/AnomalyCLIP/issues/10#issuecomment-1974920657) that you are planning to release the code, but it's still not available. Thanks!

**Comment by luca-zanella-dvl** [comment]
Hi Bogdan,

Thank you for your interest in our work! We used the class label information contained in the ShanghaiTech semantic annotations provided by one of the ShanghaiTech authors, which we found in this GitHub [repository](https://github.com/StevenLiuWen/sRNN_TSC_Anomaly_Detection/issues/10). We have uploaded the videos divided by categories [here](https://drive.google.com/file/d/1BqUiiAFlu-50mwKf-d0_mDTenv3FwpyC/view?usp=sharing). I hope this helps!

**Comment by KyloRen1** [comment]
Thank you very much. @luca-zanella-dvl, do you have the same folder with frames for XD-Violence and UCF-Crime? Thank you!
