### ISSUE TITLE
About using CLIP to extract video features

### ISSUE THREAD

**Issue by ssp-seven** [lucazanella/AnomalyCLIP#12]
May I ask how you specifically use CLIP to extract video features? Has specific code been provided? Thank you very much for your reply!

**Comment by lucazanella** [comment]
Hi,

We used the ViT-B/16 model from [CLIP](https://github.com/openai/CLIP) to extract the features. While we haven't included the code snippet for this, you can save the features after line [L121](https://github.com/luca-zanella-dvl/AnomalyCLIP/blob/ffb0aa623e2db755c195f708eeba7fb49a1c4b01/src/models/components/anomaly_clip.py#L121C17-L123C69). For a code example without the hydra template, refer to this issue #8 where the author was able to get the same features as those uploaded to Google Drive. Importantly, make sure you first convert all videos to frames using OpenCV.

If you have any further questions, feel free to ask!

**Comment by ssp-seven** [comment]
> Hi,
> 
> We used the ViT-B/16 model from [CLIP](https://github.com/openai/CLIP) to extract the features. While we haven't included the code snippet for this, you can save the features after line [L121](https://github.com/luca-zanella-dvl/AnomalyCLIP/blob/ffb0aa623e2db755c195f708eeba7fb49a1c4b01/src/models/components/anomaly_clip.py#L121C17-L123C69). For a code example without the hydra template, refer to this issue #8 where the author was able to get the same features as those uploaded to Google Drive. Importantly, make sure you first convert all videos to frames using OpenCV.
> 
> If you have any further questions, feel free to ask!

Thank you very much. This will be very helpful for my future practice.
